collegeproject/college/urls.py
from . import views
from django.urls import path
app_name='college'

urlpatterns = [
    # path('',views.index,name='index'),
    path('',views.allDepartments,name="allDepartments"),
    path('placeorder/',views.placeorder,name='placeorder'),
    path('get_courses/<str:department_name>/',views.get_courses,name='get_courses'),

    ]

collegeproject/collegeproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from collegeproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('college.urls')),
    path('credentials/',include('credentials.urls'))
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

collegeproject/credentials/urls.py
from . import views
from django.urls import path
app_name='credentials'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout',views.logout,name='logout'),


]

collegeproject/college/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Departments(models.Model):
    name=models.CharField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='department'
        verbose_name_plural='departments'


    def __str__(self):
        return '{}'.format(self.name)

class Courses(models.Model):
    name=models.CharField(max_length=250,unique=True)
    # slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)

    department=models.ForeignKey(Departments,related_name="course",on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'course'



    def __str__(self):
        return '{}'.format(self.name)

class Purposes(models.Model):
    name=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return '{}'.format(self.name)

class Materials(models.Model):
    name=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return '{}'.format(self.name)

class Order(models.Model):

    name=models.CharField(max_length=250,null=True)
    # slug=models.SlugField(max_length=250,unique=True)

    dob = models.DateField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=250,null=True, blank=True)
    mobile = models.IntegerField(null=True, blank=True)

    email = models.TextField(max_length=100)
    address = models.TextField(max_length=250)
    department= models.CharField(max_length=250,null=True)
    course = models.CharField(max_length=250,null=True)
    purpose =models.CharField(max_length=250,null=True, blank=True)
    materials = models.CharField(max_length=250,null=True, blank=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'order'
    def __str__(self):
        return '{}'.format(self.name)

collegeproject/credentials/models.py
from django.db import models

collegeproject/college/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Departments, Courses,Purposes,Materials,Order
from datetime import date
# Create your views here.
# def index(request):
# #   obj1=Team.objects.all()
#     return render(request,"index.html")
def allDepartments(request):
      departs=Departments.objects.all()
      return render(request,"index.html",{'departs':departs})

def placeorder(request):
    # departs = Departments.objects.all()
    # return render(request,'placeorder.html',{'departs':departs})
    if request.method == 'POST':
        name=request.POST.get('name')

        dob = request.POST.get('dob')

        age = request.POST.get('age')

        #gender = str(request.POST["gender"].value)
        gender = request.POST.get('gender')
        if(gender=='option1'):
            gender="Female"
        else:
            gender="Male"

        mobile = request.POST.get('mobile')
        email = request.POST.get('email')
        address = request.POST.get('address')

        department = request.POST.get("department")

        print('depart:',  department)
        course = request.POST.get('course')
        print('course:', course)
        purpose = request.POST.get('purpose')
        print('purpose:', purpose)
        materials=request.POST.getlist('checks[]')

        data = Order.objects.create(name=name, dob=dob,age=age,gender=gender,mobile=mobile,email=email,address=address,department=department,course=course,purpose=purpose,materials=materials)

        data.save()
        return redirect('/')
    departs = Departments.objects.all()
    purpose = Purposes.objects.all()
    materials=Materials.objects.all()
    return render(request,'order.html',locals())

def get_courses(request,department_name):
    department=Departments.objects.get(name=department_name)
    course=list(department.course.all().values())
    return JsonResponse(course,safe=False)

collegeproject/credentials/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from college.models import Departments
from datetime import date

# def calculate_age(born):
#     today = date.today()
#     try:
#         birthday = born.replace(year=today.year)
#     except ValueError: # raised when birth date is February 29 and the current year is not a leap year
#         birthday = born.replace(year=today.year, month=born.month+1, day=1)
#     if birthday > today:
#         return today.year - born.year - 1
#     else:
#         return today.year - born.year

# Create your views here.
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid credentials")
            return render(request,'login.html')
    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')


def register(request):
    if request.method == 'POST':

        username=request.POST.get('username')
        firstname = request.POST.get('firstname')
        password = request.POST.get('password')
        cpassword = request.POST.get('password1')
        value = {
            "username": username,
            "firstname": firstname,
             }

        error_message=None

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                    error_message='User name already exist..'

        else:
            error_message="Passwords not matched"


        if not error_message:
            user = User.objects.create_user(username=username, first_name=firstname,
                                            password=password)
            user.save()
            return redirect('/credentials/login')
        else:
            data={
                'error' :error_message,
                'values':value
            }
            return render(request, 'register.html',data)
    return render(request,'register.html')

collegeproject/templates/footer.html
<style>
 .page-footer{
bottom:1;
width:100%;
min-height:10%;
background-color:RosyBrown;
}


</style>
<!--<div class="footer navbar-fixed-bottom my-footer">-->
<!--    <p class="text-center text-white">&copy; My choice pvt Ltd. All rights reserved</p>-->
<!--</div>-->

<footer class="page-footer font-small" style="height:2rem">
    <div class="footer-copyright text-center text-white" ><br>© My college store. All rights reserved
    <a href="/"> &nbsp;onlinestore.com</a>
  </div>
  <!-- Copyright -->
</footer>
<br>

collegeproject/templates/footer1.html
{% load static %}
<footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5">
              <h2 class="ftco-heading-2">Recent Blog</h2>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({%static 'images/image_1.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> June 27, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-5 d-flex">
                <a class="blog-img mr-4" style="background-image: url({%static 'images/image_2.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> June 27, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Home</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>About</a></li>
                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Services</a></li>

                <li><a href="#"><span class="ion-ios-arrow-round-forward mr-2"></span>Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2">Subscribe Us!</h2>
              <form action="#" class="subscribe-form">
                <div class="form-group">
                  <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
                  <input type="submit" value="Subscribe" class="form-control submit px-3">
                </div>
              </form>
            </div>
            <div class="ftco-footer-widget mb-5">
            	<h2 class="ftco-heading-2 mb-0">Connect With Us</h2>
            	<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Online college Store
          </div>
        </div>
      </div>
    </footer>

collegeproject/templates/header.html
<style>
        .card-registration{
        background-color:Lavender;

        }

        #ftco-navbar{
        background-color:RosyBrown;
        font-size: 17px;
        font-weight: 600;
        color:#B8860B;
         }
    </style>

<nav class="navbar navbar-expand-lg  py-2 mt-1 pb-1" id="ftco-navbar">
	    <div class="container d-flex align-items-center px-4 mt-1">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
                   {% if user is authenticated %}
				 <h5 style="color:brown">Hello {{user.username}} ,&nbsp; &nbsp; &nbsp; &nbsp;</h5>
				   {% else %}
	        	<li class="nav-item active"><a href="/" class="nav-link pl-0">Home&nbsp; &nbsp;&nbsp; &nbsp;</a></li>

				<li class="nav-item"><a href="{% url 'credentials:logout' %}" class="nav-link">Logout&nbsp; &nbsp;&nbsp; &nbsp;</a></li>
	          <li class="nav-item"><a href="#" class="nav-link">Contact&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a></li>
                  {% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>

<div class="bg-image mt-1" style="background-image: url('https://images.adsttc.com/media/images/573c/90c0/e58e/ce1e/1600/0007/newsletter/Here_is_a_theater_to_unfold_an_outstanding_drama__and_the_characters_are_book_lovers_sitting_on_the_soft_couch_or_standing_beside_the_bookshelves._0004.jpg?1463587001');
    height: 25vh;">
</div>

collegeproject/templates/login.html
{% load static %}
{% include 'header.html' %}

<head>
    <meta charset="UTF-8">
    <title>Login</title>

<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">-->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

<style>
    h4{
    color:red;
    }

    .contain{
    background-color:CadetBlue;
    }
    body {
  background-image: url('https://img.freepik.com/free-vector/golden-bokeh-light-effect-beautiful-background_1017-36385.jpg');
}
    </style>
</head>
<body>


    <!-- Right -->
<div class="container mt-1 mb-1">
<div class=" row d-flex align-items-center justify-content-center">
<div class="p-5 col-sm-6  contain">
<form action="" method="post">
  {%csrf_token %}
  <div class="form-outline mt-4">

    <label class="form-label" for="form2Example1">Enter username: </label>
    <input type="text" name="username" class="form-control" />
  </div>

  <!-- Password input -->
  <div class="form-outline1">

    <label class="form-label" for="form2Example2">Enter Password</label>
    <input type="password" name="password" class="form-control" />
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check  text-center">
        <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked>
        <label class="form-check-label" for="form2Example31"> Remember me </label>
      </div>
    </div>

    <div class="col text-center">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
    </div>
  </div>

  <!-- Submit button -->
  <div class="row d-flex">
    <div class="col-md-3">
  <input type="Submit" value="Sign In" class="btn btn-primary btn-block mb-4"></div>
  <div class="col-md-9">
    {% for i in messages %}
    <h4>{{i}}</h4>
{% endfor %}
  </div></div>
  <!-- Register buttons -->
  <div class="text-center">
    <p>Not a member? <a href="{% url 'credentials:register' %}">Register</a></p>
    <p>or sign up with:</p>
    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-facebook-f"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-google"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-twitter"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-github"></i>
    </button>
  </div>
</form>

</div>


</div>
</div>
{% include 'footer.html' %}
</body>

collegeproject/templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Place Your Order Here</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>


    <style>
        .card-registration{
        background-color:Lavender;

        }

        #ftco-navbar{
        background-color:#D4A017;
        font-size: 17px;
        font-weight: 600;
        color:#B8860B;
         }
    </style>
    <script>
    function getCourses()
    {
        let depart=document.getElementById('depart');
        course.innerHTML = '';
        course.innerHTML = `<option selected>Select Course</option>`

         let url=`/get_courses/${depart.value}/`;
            fetch(url,{
            method: "GET",
            headers: {
            'Content-Type' : 'application/json',
            'Accept' : 'application/json'
            }
           })
          .then(response => {
                return response.json();
              })
          .then(data => {

            for(let d of data){
                course.innerHTML += `<option>${d.name}</option>`
                console.log(data);
                }
            })
          .catch(error => {
          console.log(error)
          })
    }


    function getAge(){

    var userinput = document.getElementById('dob').value;
    var dob = new Date(userinput);

    //calculate month difference from current date in time
    var month_diff = Date.now() - dob.getTime();

    //convert the calculated difference in date format
    var age_dt = new Date(month_diff);

    //extract year from date
    var year = age_dt.getUTCFullYear();

    //now calculate the age of the user
    var age = Math.abs(year - 1970);

    //display the calculated age
    document.getElementById('age').value = age;
    }

</script>

</head>
<body>
<nav class="navbar navbar-expand-lg  py-2 mt-1 pb-1" id="ftco-navbar">
	    <div class="container d-flex align-items-center px-4 mt-1">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">

				 <h5 style="color:brown">Hello {{user.username}} ,&nbsp; &nbsp; &nbsp; &nbsp;</h5>
	        	<li class="nav-item active"><a href="/" class="nav-link pl-0">Home&nbsp; &nbsp;&nbsp; &nbsp;</a></li>

				<li class="nav-item"><a href="{% url 'credentials:logout' %}" class="nav-link">Logout&nbsp; &nbsp;&nbsp; &nbsp;</a></li>
	          <li class="nav-item"><a href="#" class="nav-link">Contact&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>

<div class="bg-image" style="background-image: url('https://media.cntraveler.com/photos/5edf98c162bb344a7a7bab53/16:9/w_1920,c_limit/SistersUptownBooks-NYC-WTJ2W3.jpg');
    height: 115vh;">
<section class="vh-100 gradient-custom">
  <div class="container py-4 h-80">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-12 col-xl-12">
        <div class="card shadow-2-strong card-registration"  style="border-radius: 15px;">
          <div class="card-body p-1 p-md-4">
            <h3 class="mb-1 pb-1 pb-md-0 mb-md-4">Place your Order Here </h3>
            <div>
              <form action="" method="post" name="form1" class="mx-1 mx-md-4" onsubmit="return validate()" autocomplete="off">
                    {%csrf_token %}
                     {% if error %}
                     <div class="alert alert-danger" role="alert">
                         <h6 style="color:red">{{error}}</h6>
                     </div>
                     {% endif %}
              <div class="row">
                 <div class="col-md-6 mb-3">
                   <div class="form-outline">
                      <label class="form-label"><b>Enter your Name:*</b></label>
                      <input type="text" name="name" class="form-control" required/>
                    </div>
                 </div>

                <div class="col-md-6 mb-3">
                  <div class="form-outline">
                     <label class="form-label" ><b>Enter your DOB:*</b></label>
                    <input type="date" id="dob" name="dob" class="form-control" onchange="getAge()" required/>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <label class="form-label" ><b>Enter your Age:*</b></label>
                    <input type="text" id="age" name="age" class="form-control" readonly/>
                  </div>

                </div>
                <div class="col-md-6 mb-3">

                  <h6 class="mb-2 pb-1">Gender: </h6>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="femaleGender"
                      value="option1" required />
                    <label class="form-check-label" name="Female" for="femaleGender" >Female</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="maleGender"
                      value="option2" required/>
                    <label class="form-check-label" for="maleGender">Male</label>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3 pb-1">

                  <div class="form-outline">
                    <label class="form-label"><b>Enter your Mobile Number:*</b></label>
                    <input type="number" name="mobile" class="form-control" required/>
                  </div>
                </div>

                <div class="col-md-6 mb-3 pb-1">
                  <div class="form-outline">
                    <label class="form-label" ><b>Enter your Email:*</b></label>
                    <input type="email" name="email" class="form-control" required/>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12 mb-3 pb-1">
               <label class="form-label" ><b>Enter your Address:*</b></label>
                <input type="text" name="address" class="form-control" required/>
                </div>
              </div>

            <div class="row">

              <div class="col-md-6 mb-3 pb-1">
                <label class="form-label"><b>Department:*</b></label>

                <select id="depart" onchange="getCourses()" name="department" required>
                  <option selected>Select Department</option>
                  {% for i in departs %}
                      <option>{{i.name}}</option>
                  {% endfor %}
                </select>

                </div>
              <div class="col-md-6 mb-3 pb-1">
                <label class="form-label"><b>Courses:*</b></label>
                   <select  id="course"  name="course" required>
                      <option selected>Select Course</option>
                          {% for i in course %}
                      <option>{{i.name}}</option>
                         {% endfor %}
                   </select>

                </div>
              </div>
            <div class="row">
              <div class="col-md-6 mb-3 pb-1">
                <label class="form-label"><b>Purpose:* </b></label>

                      <select id="purpose" name="purpose"  required>
                      <option selected>Select Purpose</option>
                          {% for i in purpose %}
                      <option>{{i.name}}</option>
                         {% endfor %}
                      </select>

              </div>
              <div class="col-md-6 mb-3 pb-1">
                <label class="form-label"><b>Materials provide:*&nbsp; &nbsp;</b></label>
                         {% for i in materials %}
                      <input type="checkbox" name="checks[]" id="{{i.id}}"  value="{{i.name}}">
                      <label for="{{i.id}}"> {{i.name}}</label>&nbsp;
                         {% endfor %}
              </div>
            </div>
            <div class="row">
            <div class="col-12 text-center">
                <input type="submit" class="btn btn-primary w-100" id="submit" value="PLace Order">
            </div>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

</section>
</div>
<div class="row">
{% include 'footer.html' %}
</div>
</body>
</html>